frame_id: map
locations:
  microwave:
    frame_id: map
    position:
      x: 1.993262
      y: -2.296611
      z: 0.000363
    orientation:
      x: 0.000164
      y: 7.1e-05
      z: -0.888907
      w: 0.458088
  fridge:
    frame_id: map
    position:
      x: 2.76752
      y: -1.113858
      z: -0.000152
    orientation:
      x: -4.2e-05
      y: 1.3e-05
      z: -0.885754
      w: 0.464156
  sink:
    frame_id: map
    position:
      x: 1.993262
      y: -2.296611
      z: 0.000363
    orientation:
      x: 0.000164
      y: 7.1e-05
      z: -0.888907
      w: 0.458088
  table:
    frame_id: map
    position:
      x: -1.35569
      y: 0.522279
      z: 8.9e-05
    orientation:
      x: -5.9e-05
      y: -8.7e-05
      z: -0.954028
      w: -0.299716
  kitchen_exit:
    frame_id: map
    position:
      x: 3.009724
      y: -0.956881
      z: 0.000129
    orientation:
      x: 3.8e-05
      y: -1.2e-05
      z: -0.998619
      w: -0.052539
