frame_id: map
locations:
  microwave:
    frame_id: map
    position:
      x: 0.672016
      y: -0.103017
      z: -0.000337
    orientation:
      x: 3.1e-05
      y: -0.000122
      z: 0.001117
      w: 0.999999
  fridge:
    frame_id: map
    position:
      x: -1.883541
      y: -0.061578
      z: 0.000223
    orientation:
      x: -0.000126
      y: 1.8e-05
      z: 0.057535
      w: 0.998343
  sink_a:
    frame_id: map
    position:
      x: -0.217657
      y: 0.006646
      z: -0.000147
    orientation:
      x: 7.3e-05
      y: -8.0e-06
      z: 0.693298
      w: 0.720651
  refrigerator_a:
    frame_id: map
    position:
      x: 1.455591
      y: 0.020929
      z: 0.000202
    orientation:
      x: -6.1e-05
      y: -2.6e-05
      z: 0.999395
      w: 0.034792
  microwave_new:
    frame_id: map
    position:
      x: 3.546214
      y: -0.508975
      z: -0.0001
    orientation:
      x: -9.7e-05
      y: -9.0e-06
      z: 0.633856
      w: 0.773451
  refrigerator:
    frame_id: map
    position:
      x: -1.550198
      y: 0.43276
      z: -9.7e-05
    orientation:
      x: 4.8e-05
      y: -2.4e-05
      z: -0.091617
      w: 0.995794
  sink_new:
    frame_id: map
    position:
      x: 3.258858
      y: -0.385241
      z: -6.9e-05
    orientation:
      x: 6.8e-05
      y: -9.0e-06
      z: 0.833876
      w: -0.551952
  sink_easy:
    frame_id: map
    position:
      x: -0.360847
      y: -0.061332
      z: -0.000122
    orientation:
      x: -2.9e-05
      y: -5.8e-05
      z: -0.968979
      w: 0.247142
  microwave_easy:
    frame_id: map
    position:
      x: -0.391672
      y: -0.018109
      z: -4.9e-05
    orientation:
      x: -2.0e-06
      y: -4.3e-05
      z: -0.716221
      w: 0.697873
  refrigerator_easy:
    frame_id: map
    position:
      x: 1.225298
      y: 1.864621
      z: -5.0e-05
    orientation:
      x: -3.1e-05
      y: -1.8e-05
      z: -0.869588
      w: 0.493778
  sink:
    frame_id: map
    position:
      x: -0.18616
      y: -0.084078
      z: 0.000175
    orientation:
      x: 0.000213
      y: 4.3e-05
      z: -0.111031
      w: 0.993817
  outside:
    frame_id: map
    position:
      x: -2.318987
      y: -1.2524
      z: -0.000687
    orientation:
      x: 0.000102
      y: -0.000145
      z: 0.658205
      w: 0.752839
  table:
    frame_id: map
    position:
      x: 1.590877
      y: 0.289144
      z: -0.000134
    orientation:
      x: 2.4e-05
      y: -4.2e-05
      z: -0.042934
      w: 0.999078
